### ISSUE TITLE
Generate response below cursor instead of at note end

### ISSUE THREAD

**Issue by FelixBrakel** [bramses/chatgpt-md#14]
If your notes have a footer then this plugin will stream in the ChatGPT response to your prompt below it currently. I think it would be preferable if the response is placed below the cursor instead.

Otherwise amazing plugin, adding this to my vault was an absolute no-brainer.

**Comment by bramses** [comment]
Hi @FelixBrakel, 

That's a great idea. I'll add a toggle in the settings of the next release to control that.

**Comment by bramses** [comment]
Added with new release: https://github.com/bramses/chatgpt-md/releases/tag/1.1.0
