### ISSUE TITLE
Real Streaming

### ISSUE THREAD

**Issue by lukemt** [bramses/chatgpt-md#19]
Hi!

I was wandering if the streaming functionality isn't actually real streaming but rather an animation, because the completions take quite a while to start. 

If this is the case then maybe we can implement real streaming of the responses?

I found a working example with typescript here:
https://github.com/whichlight/chatgpt-api-streaming

**Comment by lukemt** [comment]
I'd be happy to help btw :)

**Comment by bramses** [comment]
Hi @lukemt, good idea, I'm not sure if it will work in Obsidian but I'll look into it. Thanks for the resource!

**Comment by lukemt** [comment]
Yeah let's hope this works. I found the example after failing to get davinci and gpt-4 to code the thing. Somehow Bing did find this zero star repo

**Comment by bramses** [comment]
Fixed by https://github.com/bramses/chatgpt-md/releases/tag/1.2.0 ! Check it out!
