### ISSUE TITLE
New chat from template doesn't work if `chats` folder is missing

### ISSUE THREAD

**Issue by Maximilian-Staab** [bramses/chatgpt-md#28]
Steps to reproduce:
1. delete `ChatGPT_MD/chats` folder
2. select `Create new chat from template` from the command menu
3. watch as nothing happens

Steps to troubleshoot:
1. create  `ChatGPT_MD/chats` folder

**Comment by bramses** [comment]
Thanks for the issue @Maximilian-Staab I can have it raise a notice, but this functionality is intended. A `chat` and `templates` folder are required.

**Comment by Maximilian-Staab** [comment]
Thanks for the quick response Bram, but there seems to be some confusion about this issue. Setting a folder for `templates` and `chats` is documented in the Readme, but I assume a user would still expect the folder to be created automatically if it's missing. Either that or a popup message telling the user about the missing folder (+ button for creating it quickly). 

Right now, without a notification or documentation in the Readme, the user might assume that the template feature is broken.

**Comment by bramses** [comment]
Hmm gotcha, good point both. I'll add a modal to create default folders as an FR.
