### ISSUE TITLE
Infer title error

### ISSUE THREAD

**Issue by NightOwlCoder** [bramses/chatgpt-md#30]
After using for a while, looks like I end up with 2 sessions with the same name:
```
app.js:1 Uncaught (in promise) Error: Destination file already exists!
    at e.<anonymous> (app.js:1:1102941)
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)
```

**Comment by bramses** [comment]
Hi @NightOwlCoder, it probably inferred a title that's the same as another in your folder. You can see what it inferred in the console. Try renaming one and lmk!

**Comment by NightOwlCoder** [comment]
Yeah, I have noticed that.
But maybe the code does the usual and appends a (1..n) to the tittle?

**Comment by bramses** [comment]
Good idea, I'll put that in as a FR
