### ISSUE TITLE
Feature Request: customize API server domain

### ISSUE THREAD

**Issue by Akifyss** [bramses/chatgpt-md#34]
Hi there! Thank you for creating this amazing plugin!❤️
I was wondering if it would be possible to add a feature that allows users to customize the API server domain. It would be really helpful for those who have specific domains. Thank again for your hard work! 🙌
Here's an example:
![image](https://user-images.githubusercontent.com/23567154/227730483-18abe421-b9ba-4d4d-8b3e-d4e1402b1cdb.png)

**Comment by bramses** [comment]
Hey @Akifyss,

Yep, you can use a [custom endpoint](https://github.com/bramses/chatgpt-md#q-how-do-i-use-a-custom-endpoint) (thanks to @Nintorac!) in your frontmatter as long as it conforms to the [OpenAI API params](https://platform.openai.com/docs/api-reference/chat/create)

**Comment by Jackiexiao** [comment]
I encounter this problem... sorry , I don't know how to fix it

Access to XMLHttpRequest at 'https://chatgpt-xxxx.app/proxy' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by bramses** [comment]
Hi @Jackiexiao, 

CORS is a known problem for Obsidian. You can try making a middleware server! 

https://forum.obsidian.md/t/make-http-requests-from-plugins/15461/2
