### ISSUE TITLE
This is a feature request.

### ISSUE THREAD

**Issue by Code-Dramatist** [bramses/chatgpt-md#37]
Hello, Author. For countries where it is not possible to access ChatGPT's services directly, I would appreciate it if you could introduce a feature that allows us to customize the API proxy server address. This would greatly enhance accessibility and convenience for users in these countries.
  Thank you！

**Comment by bramses** [comment]
Hi @Code-Dramatist,

See https://github.com/bramses/chatgpt-md/issues/34

**Comment by Code-Dramatist** [comment]
thank you
