### ISSUE TITLE
Custom endpoint

### ISSUE THREAD

**Issue by Code-Dramatist** [bramses/chatgpt-md#38]
My configuration should not have any errors, right? I modified the API key in the settings panel. It seems like there is a problem with the custom terminal, but I don't know where the issue lies.

Looking forward to your reply, thank you.

![image](https://user-images.githubusercontent.com/29671214/227832796-ee30f0a6-6c83-4844-a87c-44c9a9a0966c.png)

**Comment by bramses** [comment]
I wouldn't be able to recreate this but I imagine it's something to do with CORS. If you can access logs on the server side, I'd check there. If not, your best bet may be to fork the repo, install it locally and intercept the call from Obsidian.
