### ISSUE TITLE
Feature Request: add a command to clear conversation (Except frontmatter)

### ISSUE THREAD

**Issue by Akifyss** [bramses/chatgpt-md#39]
Hello! 
I was wondering if it would be possible to add a command to clear conversation (excluding frontmatter). This would allow for a quick start to a new conversation without having to create a new file or manually select and delete the previous conversation (in order to save tokens). 

Here's an example:
![Frame 427319517](https://user-images.githubusercontent.com/23567154/228132899-c9e013a6-252f-4a06-ae10-3c0f7ad03333.png)

**Comment by bramses** [comment]
Hi @Akifyss,

Yeah I can look into it and see if it's a non breaking change

**Comment by Akifyss** [comment]
Thank a lot！❤️
