### ISSUE TITLE
Difficulty Installing Plugin

### ISSUE THREAD

**Issue by EidosL** [bramses/chatgpt-md#4]
I am having trouble installing the plugin on my computer. I am not knowledgeable in programming and am facing some difficulty with the installation process. I have followed the instructions provided but still cannot seem to get it to work.

Can someone please provide me with some guidance on how to install this plugin successfully? Perhaps a step-by-step guide or some troubleshooting tips would be greatly appreciated.

Thank you in advance for your assistance.

![image](https://user-images.githubusercontent.com/70374652/224257044-770068ab-177d-48d8-8b1f-bc19b13deba4.png)
![image](https://user-images.githubusercontent.com/70374652/224257426-41a01d6d-7825-4331-aa36-82b6b8dae088.png)

**Comment by bramses** [comment]
hi @EidosL, did you run `npm install` before `npm run build`?

**Comment by EidosL** [comment]
Thx, I fixed the problemXD
