### ISSUE TITLE
Feature request: default model

### ISSUE THREAD

**Issue by sunt05** [bramses/chatgpt-md#41]
Thanks for the great work!

Can we add an option to set default model?
I understand this can be done by inserting the front matter; however, for some prompt conversion initiated within an existing note, the model is always `got-3.5` and cannot meet my needs.

**Comment by bramses** [comment]
Hi @sunt05,

I can look into it, that's a pretty easy fix. May I ask why "model" in frontmatter is not sufficient though?

**Comment by sunt05** [comment]
Thanks for your follow-up @bramses !

Because I find if I initiate a chat in an arbitrary note by adding a chat divider, the chat is always based on GPT-3.5 though I have changed the default front matter with "model" being "GPT-4".

**Comment by lukemt** [comment]
I see many people use chatgpt-md within existing notes and I am wondering if this is an intended use case and what’s actually going on if you do that. Doesn’t chatgpt-md send the entire content of the existing note to ChatGPT as a message and if so are people aware that this happens?

I believe for most users that do this would prefer a chatgpt-md section, that is „independent“ of the rest of the note.

What do you guys think about this?

**Comment by lukemt** [comment]
My comments are a topic of its own I think. Therefore I created a new discussion for it: https://github.com/bramses/chatgpt-md/discussions/44 (should have done this in the first place)

**Comment by bramses** [comment]
closing for now since @lukemt made the discussion!
