### ISSUE TITLE
Thanks for making this and I update to version 1.5, seems the commands not available anymore

### ISSUE THREAD

**Issue by LintaoAmons** [bramses/chatgpt-md#53]
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/95092244/229677717-99b63b1c-d05d-4fc1-81b0-6b0c0d8a86ba.png">

Thanks for making this, this is really my ideal way of using the chatGPT superpower.

**Comment by bramses** [comment]
Hi @LintaoAmons,

Can you try restarting Obsidian and see if that fixes it?

**Comment by LintaoAmons** [comment]
Hi @bramses,

There are no commands even after I restart the obsidian

**Comment by bramses** [comment]
hmm idk then, its showing up fine for me in multiple vaults, perhaps check the developer tools pane and see if any error is occurring? if that doesnt work, downgrade to 1.4.3 for now?

![Screenshot 2023-04-04 07-36-16](https://user-images.githubusercontent.com/3282661/229779639-2668bb9e-489b-4607-b867-99244ebb30fc.png)
![Screenshot 2023-04-04 07-36-28](https://user-images.githubusercontent.com/3282661/229779642-cdc96479-befd-4710-b756-c6311d714606.png)

**Comment by LintaoAmons** [comment]
Yes, I currently still using the 1.4.3.
Later maybe I shall restart the computer and try it again~
