### ISSUE TITLE
Unclear how to hit "trigger" (or equivalent) the assistant to work

### ISSUE THREAD

**Issue by jasmeetchadha** [bramses/chatgpt-md#6]
I am playing around but I havent figured a consistant command or set of commands to get the assistant mode on. I have used highlighted words, chat, or template. 

chat mode works sometimes.

**Comment by bramses** [comment]
Hi @jasmeetchadha, assistant is simply the role OpenAI uses to refer to the GPT response. There are three roles in the docs: assistant, user (you) and system (basically pre rules). Does that make sense?

If you use the chat command, the plug-in parses by looking for <hr> lines and if it doesn't find any it automatically sends the current note as a user role
