### ISSUE TITLE
Are trailing spaces removed?

### ISSUE THREAD

**Issue by tophee** [bramses/chatgpt-md#60]
I just saw [on the open AI website](https://hyp.is/95d91tXjEe20Hc_EJiaNjw/help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them) that a trailing space in the user prompt may reduce the quality of the response. So I'm just curious whether ChatGPT_MD is removing them before submission.

**Comment by lukemt** [comment]
Hi @tophee 

I was wondering the same thing. I did not know if it would actually reduce the quality of the response, but I did have that thought! Thanks for the info.

To answer your question: Yes, they are removed. If you open the developer console (`Ctrl + Shift + J` for Windows and Linux, and `Cmd + Opt + J` for Mac) you can see the actual json that is sent to OpenAI.

If you need any further help, feel free to ask.

**Comment by bramses** [comment]
Hi @tophee, yeah @lukemt is correct trailing spaces are removed during message extraction pipeline. 

See https://github.com/bramses/chatgpt-md/blob/master/main.ts#L335-L340
