### ISSUE TITLE
Meet 429 error when using chat

### ISSUE THREAD

**Issue by WystanW** [bramses/chatgpt-md#61]
I can use chatgpt in the webpage. But when using it in obsidian. A 429 error returns

![image](https://user-images.githubusercontent.com/18168353/230715173-946999ef-94d6-4530-9ad3-075aabc66651.png)

**Comment by lukemt** [comment]
Strange 429 usually means too many requests, which is unlikely that you would achieve that on your own.

Does the error still happen? Is the api key configured correctly?

Otherwise try to install chatgpt-md in a sandbox vault and compare if it works there.

**Comment by bramses** [comment]
Hi @WystanW,

@lukemt is correct. 429 is an OpenAI error b/w them and client (you). Try through the UI (platform.openai.com) and see if you get a 429 there too.
