### ISSUE TITLE
Doc request: how exactly does it find connections between notes?

### ISSUE THREAD

**Issue by Richie-Peak** [bramses/chatgpt-md#65]
There are lots of plugins that do this, it would be good to know exactly how the plugin suggests notes so that users can see whether this plugin replicates other plugins they have or compliments them.

**Comment by lukemt** [comment]
Not sure if I understand the question. It does not suggest any notes as far as I know

**Comment by Richie-Peak** [comment]
Sorry, my bad, wrong repo! I had this and another repo open in side by side and this was meant for that repo

**Comment by lukemt** [comment]
I see! 😅
