### ISSUE TITLE
Add this plugin to the mobile ribbon menu

### ISSUE THREAD

**Issue by lukemt** [bramses/chatgpt-md#67]
I would like to access the `Create new chat from template` command from the mobile ribbon menu.

![image](https://user-images.githubusercontent.com/3893274/231881211-9cb8136f-4226-4210-90c3-f66f92af8c41.png)

**Comment by lukemt** [comment]
Ok, personally I don't need this anymore since I replaced the ribbon with the command palette. If anyone else would like the feature nonetheless, please comment or react to help prioritize the feature

**Comment by bramses** [comment]
@lukemt I use Commander (https://github.com/phibr0/obsidian-commander) for things like this!

**Comment by lukemt** [comment]
@bramses Good idea though, didn't think of this
