### ISSUE TITLE
Don't allow multiple in flight requests

### ISSUE THREAD

**Issue by mk-oliver-s** [bramses/chatgpt-md#68]
It is currently possible to run multple inferences in parallel. 

In streaming mode it is only possible to cancel one of them.

**Comment by mk-oliver-s** [comment]
Hey, why was this closed?

**Comment by bramses** [comment]
Hi @mk-oliver-s  

I think this is user error tbh and don't want to fix it. If you want to put in a pr I'd be happy to take a look though

**Comment by mk-oliver-s** [comment]
Ok, no problem.

I don't believe user error here but I don't have time to PR. Here is a gif of what I mean anyway

![image](https://user-images.githubusercontent.com/122239137/232352815-438e17b4-7d6d-4738-a248-e5a2c1cce337.png)
