### ISSUE TITLE
Error message `${role}\\\\n\\\\n`;' is not one of ['system', 'assistant', 'user']` when asked chatgpt to to explain code snippet

### ISSUE THREAD

**Issue by MaksimZinovev** [bramses/chatgpt-md#7]
Hi , 
Thank you for the plugin. 
I came across this issue. Probably I am doing something incorrectly. Would appreciate it if you could help me . Thanks

I can attach source file if needed.

**Preconditions:** 
1. Install and enable plugin as per instructions https://github.com/bramses/chatgpt-md

**To reproduce**
1. Create new note.
2. Paste snippet 1
3. Type question "Can you explain the above code?^" 
4. Run command "Chat GPT MD: Chat"
5. Observe response in your file , as expected.
6. Run command "Chat GPT MD: Add divider"
7. Paste snippet 2
8. Run command "Chat GPT MD: Chat"
9. Observe error message
```
Error: issue calling OpenAI API, see error for more details: Error: Error: {"message":"'${role}\\\\n\\\\n`;' is not one of ['system', 'assistant', 'user'] - 'messages.5.role'","type":"invalid_request_error","param":null,"code":null}
    at ChatGPT_MD.callOpenAIAPI (plugin:chatgpt-md:148:13)
```

**Snippet 1**

```js

console.log("Hello")
```

**Snippet 2** 

```typescript
	addHR(editor: Editor, role: string) {
		const newLine = `\n\n<hr class="__chatgpt_plugin">\n\nrole::${role}\n\n`;
		editor.replaceRange(newLine, editor.getCursor());

		// move cursor to end of file
		const cursor = editor.getCursor();
		const newCursor = {
			line: cursor.line,
			ch: cursor.ch + newLine.length,
		};
		editor.setCursor(newCursor);
	}
```
![image](https://user-images.githubusercontent.com/53397443/224514743-72b45cd8-363d-4307-85ff-1f419b9e39a4.png)

Expected result: Chat GPT should explain snippet 2 correctly.

**Environment**

1. MacOS Ventura 13.2.1
2. Obsidian 1.1.16
3. ChatGPT MD plugin: 1.0.2

**Comment by bramses** [comment]
Hi @MaksimZinovev, haha yes this is an edge case. The program "splits" messages for the ChatGPT API on that HR line `<hr...` since it all reads in as a string. So it errored because it saw that as the split. Remove that line and it will work. Does that make sense?

**Comment by MaksimZinovev** [comment]
Haha, sorry I am a bit slow :) Just realised what kind of issue I "reported". 
I wanted to test the code explain case and grabbed the first snippet I found in your repo :) The one that broke the plugin. 
I attribute this to the fact that I am a software tester :) Sometimes I break software completely unintentionally and then realise I just found a bug (or a feature:) )
