### ISSUE TITLE
How to configure the naming of chat files to custom format like yyyy-MM-dd hh:mm

### ISSUE THREAD

**Issue by tkt028** [bramses/chatgpt-md#8]
Hi there,
My personal workflow relies on file naming convention for further/later query (by my own custom scripts for that).
Is it possible that I configure the naming of chat files to custom format like yyyy-MM-dd hh:mm?

The plugin is very nice! Thank you very much! 
Bests,
TK

**Comment by bramses** [comment]
Hi @tkt028, Thanks for the suggestion, I'll try to put it into a future release.

**Comment by bramses** [comment]
Added with new release: https://github.com/bramses/chatgpt-md/releases/tag/1.1.0

**Comment by tkt028** [comment]
Thank you very much! @bramses. It works!
I enjoy the experience of interacting with chatGPT and have Obsidian to host my conversations for later query.
