### ISSUE TITLE
No chatGPT related commanders appered in the dropdown menu.

### ISSUE THREAD

**Issue by iszhi** [bramses/chatgpt-md#85]
I just installed the plugin. I love it so much. However, it didn't work problely. When I want to run the commander from ctrol+P, it didn't show up there. I don't know why.
The version of this plugin is 1.5.0 with the obsidian version 1.3.4

**Comment by lukemt** [comment]
I think the issue is #62

**Comment by iszhi** [comment]
I didn't see any commander. 
![image](https://github.com/bramses/chatgpt-md/assets/33443222/61d272d2-4f3e-48aa-914f-d0e34529403c)

**Comment by iszhi** [comment]
@lukemt Thanks. it works again after I creat a new note. Hope it can be fixed in the next version.
