### ISSUE TITLE
Critical Failure - API calls no longer working in Obsidian

### ISSUE THREAD

**Issue by AustinSanderson** [bramses/chatgpt-md#99]
API calls stop producing output or making a connection sometime within the last 24 hours.  From Obsidian, it appears the plugin is freezing on "Calling API" as it does not product any output. I have tested this on two computers and two internet connections with the same issue. I also used two different API keys and reinstalled the plugin with a new API key. Currently, there are no API outages shown on OpenAI's status page. Copilot plugin is working just fine with the same API key. Obsidian logs do not indicate any issue with the plugin, yet the problem remains persistent.

I am running version 1.5.0 on Obsidian v1.5.3

**Comment by AustinSanderson** [comment]
This appears to be an issue with the templates and/or the way Obsidian properties works in conjunction with the Stream property. The API call completes only when Stream is not checked in the Obsidian template.

**Comment by AustinSanderson** [comment]
It appears that Stream was toggled off in the plugin settings somehow during the latest Obsidian update. So while you had Stream turned on in the Frontmatter (Obsidian properties), the plugin itself had a setting which was turned off creating a conflict. Toggle Stream back on in the plugin settings, and the API calls are functioning again when Stream is set to True in the frontmatter.

**Comment by LaughingElephant** [comment]
Hey so I know this got marked as closed but I’m having the same api call issue, and the stream options don’t seam to be the culprit. The code is stuck calling the API. Stream in the frontmatter is set to true and is toggled on in the Obsidian settings. Having trouble troubleshooting this one further, wanted to see if there were any suggestions before opening a different issue

**Comment by AustinSanderson** [comment]
> Hey so I know this got marked as closed but I’m having the same api call issue, and the stream options don’t seam to be the culprit. The code is stuck calling the API. Stream in the frontmatter is set to true and is toggled on in the Obsidian settings. Having trouble troubleshooting this one further, wanted to see if there were any suggestions before opening a different issue

I ultimately had to turn off stream both in the frontmatter and in the Obsidian settings. I deleted the Stream property from my templates as it no longer works with this plugin. This way, I have no issues using the API and getting responses, but there is a wait-time to see results unfortunately. I do not know if this plugin is still maintained, but perhaps I can reopen this bug report.

**Comment by LaughingElephant** [comment]
Awesome thanks that did it for now
